import sys

s = """
Em không hiểu.
Em không hiểu!!
Em không hiểu nổi mấy người có vấn đề gì! Em không hiểu nổi những cái meme mấy người làm! Em không hiểu! Em không hiểu! Tại sao Goku lại có drip? Và anh ấy là nhân vật hoạt hình, không phải phản động! Mỉa mai về Đổi Mới thì có gì hay? Bộ muốn sống mãi ở thời Bao Cấp sao? Rick là ai? Tại sao anh ấy lại lăn? Tại sao cái link ấy xuất hiện ở khắp nơi? Tại sao em bé lại biến thành chiếc xe? Tại sao phi hành gia lại ở trong đại dương? "Con chó đang làm gì"? Ai mà biết được? Vin Diesel thì sao? Dominic Toretto thì sao? Gia đình thì sao? Mấy thứ đó thật sự hài hước đến vậy à? "B* c* để giảng hoà, để mọi chuyện được em xuôi" hả? Thật nực cười! Điều đó chỉ khiến nó gay hơn thôi! Bây giờ không còn là những năm 2010s nữa. Rage Comic, Trollface đã chết rồi! Vậy những cái meme dầu ăn, incident, dementia. Tại sao chúng nó lại xuất hiện? Làm người không làm, sao lại muốn quay về làm khỉ? Những cái meme bàn ủi ở bên dưới giải thích là sao? Đúng là vô nghĩa! Và đừng dùng những từ lóng nữa! Em không thể nào theo kịp! Đừng nói "Trong trường hợp" khi muốn nói mình yêu nước! Đừng nói "anh bạn à" khi muốn nói về b* c*! Sussy baka, Sus, Imposter, Amogus! Tệ nhất là chúng nó, những cái meme Jojo thậm chí còn không liên quan. Đừng có comment về Jojo nữa! Em chán phải thấy nó rồi! Bạn bè trên Tik Tok gửi em memes, trên Discord thì memes chết tiệt của nó! Em đã ở trong 1 server, đúng chứ? Và tất cả các kênh chỉ toàn là thứ Jộ! Rồi Shroomjak là cái gì? Người hay nấm? Em không hiểu! Những từ ngữ cũng khó hiểu nữa! "Chad", "Virgin", "Fan", "Enjoyer",... Ý của mấy người là gì khi nói "Sigma Male"? Em không thể hiểu được nội dung chỉ bằng vài từ ngữ! Chía đang làm gì trong những cái meme? Có liên quan đến chủ đề chút nào không? Và em sẽ không cảm ơn Chía đâu vì cô ta không có thật! Cá rô phi là 1 món ăn ngon, không phải thứ dùng để phân biệt vùng miền! Những lúc chúng ta nói chuyện, em nói ra quan điểm cá nhân thì anh nói "ai hỏi?". Đến khi em tức giận thì anh nói "anh chỉ đang chôn tí thôi mà.". EM KHÔNG HIỂU! Nói chuyện với em như người bình thường đi! Em cầu xin anh, hãy thuyết phục em rằng anh tốt hơn bộ phận những người "Socially inept" đi! Là memer thì có gì hay? Là "man of culture" thì ngầu lắm sao? Em không hiểu! Em không hiểu! Em không hiểu! Em không hiểu! EM KHÔNG HIỂU!!! Là thành viên của Hang Pác Pó thì có gì là tuyệt vời chứ? EM KHÔNG HIỂU!!!
"""
s = s.encode("utf-8")

sys.stdout.buffer.write(s)